apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:

      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: hello-world
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
